/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_docente.visual.EvaluationVisual;

import gestion_docente.dto.*;
import gestion_docente.services.*;
import gestion_docente.services.ServicesLocator;
import gestion_docente.visual.AcademicsYearsVisual;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author César
 */
public class EvaluationsVisual extends javax.swing.JPanel {

    /**
     * Creates new form EvaluationsVisual
     */
    public EvaluationsVisual() {
        initComponents();
        cargarEvals();
    }
    
    private void cargarEvals() {
        EvaluationServices ay = ServicesLocator.getEvaluationServices();
        
        try {
            ArrayList<EvaluationDTO> listDTO = ay.getAllEvaluations();
            evaluationsTable.setModel(new DefaultTableModel(evalsToMatriz(listDTO),
                new String[]{"Estudiante", "Asignatura","Evaluación"}));
        } catch (SQLException ex) {
            Logger.getLogger(AcademicsYearsVisual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EvaluationsVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public Object[][] evalsToMatriz(ArrayList<EvaluationDTO> datos) throws SQLException {
        // Convierte el ArrayList a Object[][]
        Object[][] objectArray = new Object[datos.size()][3];

        for (int i = 0; i < datos.size(); i++) {
            for (int j = 0; j < 3; j++) {
                if (j == 0) {
                    StudentServices ss = ServicesLocator.getStudentServices();
                    String estudiante = ss.getStudentById(datos.get(i).getId_student());
                    objectArray[i][j] = estudiante;
                }
                if (j == 1) {
                    
                    SubjectServices ss = ServicesLocator.getSubjectServices();
                    String asignatura = ss.getSubjectById(datos.get(i).getId_subject());
                    
                    objectArray[i][j] = asignatura;
                }
                
                if (j == 2) {
                    objectArray[i][j] = datos.get(i).getEvaluation();
                }
                
            }

        }
        return objectArray;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        evaluationsTable = new javax.swing.JTable();

        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        evaluationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student", "Subject", "Evaluation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(evaluationsTable);
        if (evaluationsTable.getColumnModel().getColumnCount() > 0) {
            evaluationsTable.getColumnModel().getColumn(0).setResizable(false);
            evaluationsTable.getColumnModel().getColumn(1).setResizable(false);
            evaluationsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CreateEvaluation createEvaluation = new CreateEvaluation();
        createEvaluation.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if ((evaluationsTable.getSelectedRow()) != -1) {//se selecciono una fila
            EvaluationServices ss = ServicesLocator.getEvaluationServices();

            try {
                //obtengo todos los estudiantes
                ArrayList<EvaluationDTO> evals = ss.getAllEvaluations();
                EvaluationDTO seleccion = evals.get(evaluationsTable.getSelectedRow());
                int id = seleccion.getId();
                if (JOptionPane.showConfirmDialog(null, "Desea eliminar la evaluación" + seleccion) == 0) {
                    if (ss.delete_object(id, EvaluationServices.DELETE_EVALUATION)) {
                        JOptionPane.showMessageDialog(null, "Evaluación eliminado correctamente");

                    } else {
                        JOptionPane.showMessageDialog(null, "Evaluación no fue eliminado correctamente");
                    }
                }
                //actualizar tabla students
                cargarEvals();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió una excepción" + ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(EvaluationsVisual.class.getName()).log(Level.SEVERE, null, ex);
              }

        } else {//no se selecciono ninguna fila

            JOptionPane.showMessageDialog(null, "Seleccione una evaluación antes de intentar eliminar");
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable evaluationsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
