/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_docente.visual;

import gestion_docente.services.*;
import gestion_docente.dto.*;
import gestion_docente.visual.StudentVisual.DeleteStudent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author César
 */
public class AcademicsYearsVisual extends javax.swing.JPanel {

    /**
     * Creates new form AniosAcademicosVisual
     */
    public AcademicsYearsVisual() {
        initComponents();
        cargarAnios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        academicsYearsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        academicsYearsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Año", "Curso escolar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(academicsYearsTable);
        if (academicsYearsTable.getColumnModel().getColumnCount() > 0) {
            academicsYearsTable.getColumnModel().getColumn(0).setResizable(false);
            academicsYearsTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CreateAcademicsYear createAcademicsYear = new CreateAcademicsYear();
        createAcademicsYear.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if ((academicsYearsTable.getSelectedRow()) != -1) {//se selecciono una fila
            AcademicYearServices ss = ServicesLocator.getAcademicYearServices();

            try {
                //obtengo todos los estudiantes
                ArrayList<YearDTO> estudiantes = ss.getYears();
                YearDTO seleccion = estudiantes.get(academicsYearsTable.getSelectedRow());
                int id = seleccion.getId();
                if (JOptionPane.showConfirmDialog(null, "Desea eliminar el año" + seleccion) == 0) {
                    if (ss.delete_object(id, AcademicYearServices.DELETE_YEAR)) {
                        JOptionPane.showMessageDialog(null, "Año eliminado correctamente");

                    } else {
                        JOptionPane.showMessageDialog(null, "Año no fue eliminado correctamente");
                    }
                }
                //actualizar tabla students
                cargarAnios();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió una excepción" + ex);
            }

        } else {//no se selecciono ninguna fila

            JOptionPane.showMessageDialog(null, "Seleccione un año antes de intentar eliminar");
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable academicsYearsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void cargarAnios() {
        AcademicYearServices ay = ServicesLocator.getAcademicYearServices();

        try {
            ArrayList<YearDTO> listDTO = ay.getYears();
            academicsYearsTable.setModel(new DefaultTableModel(yearsToMatriz(listDTO),
                    new String[]{"Año", "Curso Escolar"}));
        } catch (SQLException ex) {
            Logger.getLogger(AcademicsYearsVisual.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public Object[][] yearsToMatriz(ArrayList<YearDTO> datos) throws SQLException {
        // Convierte el ArrayList a Object[][]
        Object[][] objectArray = new Object[datos.size()][2];

        for (int i = 0; i < datos.size(); i++) {
            for (int j = 0; j < 2; j++) {
                if (j == 0) {
                    objectArray[i][j] = datos.get(i).getYear();
                }
                if (j == 1) {
                    objectArray[i][j] = datos.get(i).getSchollar_course();
                }

            }

        }
        return objectArray;

    }
}
