/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_docente.visual;

import gestion_docente.dto.GroupDTO;
import gestion_docente.services.GroupServices;
import gestion_docente.services.ServicesLocator;
import gestion_docente.services.StudentServices;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author César
 */
public class GroupsVisual extends javax.swing.JPanel {

    /**
     * Creates new form GroupsVisual
     */
    public GroupsVisual() {
        initComponents();
        try {
            llenarGroupsTable();
        } catch (SQLException ex) {
            Logger.getLogger(GroupsVisual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GroupsVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupsTable = new javax.swing.JTable();

        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        groupsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Number group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        groupsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(groupsTable);
        if (groupsTable.getColumnModel().getColumnCount() > 0) {
            groupsTable.getColumnModel().getColumn(0).setResizable(false);
            groupsTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CreateGroup crearGroup = new CreateGroup();
        crearGroup.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if ((groupsTable.getSelectedRow()) != -1) {//se selecciono una fila
            GroupServices gs = ServicesLocator.getGroupServices();

            try {
                //obtengo todos los estudiantes
                ArrayList<GroupDTO> grupos = gs.getAllGroups();
                GroupDTO grupoSeleccionado = grupos.get(groupsTable.getSelectedRow());
                int id = grupoSeleccionado.getId();
                if (JOptionPane.showConfirmDialog(null, "Desea eliminar el grupo " + grupoSeleccionado) == 0) {
                    if (gs.delete_object(id, StudentServices.DELETE_GROUP)) {
                        JOptionPane.showMessageDialog(null, "Grupo eliminado correctamente");

                    } else {
                        JOptionPane.showMessageDialog(null, "Grupo no fue eliminado correctamente");
                    }
                }
                //actualizar tabla students
                llenarGroupsTable();
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió una excepción" + ex);
            }

        } else {//no se selecciono ninguna fila

            JOptionPane.showMessageDialog(null, "Seleccione un grupo antes de intentar borrarlo");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public void llenarGroupsTable() throws SQLException, ClassNotFoundException {

        GroupServices gs = ServicesLocator.getGroupServices();
        ArrayList<GroupDTO> datos = gs.getAllGroups();

        groupsTable.setModel(new DefaultTableModel(groupsToMatriz(datos),
                new String[]{"Año", "Grupo"}));

    }

    public Object[][] groupsToMatriz(ArrayList<GroupDTO> datos) {
        // Convierte el ArrayList a Object[][]
        Object[][] objectArray = new Object[datos.size()][2];

        for (int i = 0; i < datos.size(); i++) {
            for (int j = 0; j < 2; j++) {
                if (j == 0) {
                    objectArray[i][j] = datos.get(i).getYear();
                }
                if (j == 1) {
                    objectArray[i][j] = datos.get(i).getNum_group();
                }
            }

        }
        return objectArray;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable groupsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
